# Generated by Django 4.2.23 on 2025-07-14 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='about',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
